#!/bin/bash
set -u
export ROOT_DIR=$PWD
export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH
cd $GOPATH/src/github.com/cloudfoundry/cf-smoke-tests/


if [ ! -f "$ROOT_DIR/env/metadata" ]; then
  echo "Env. file do not exist"
  exit 1
fi


file_data=$(cat $ROOT_DIR/env/metadatas)

#compiling smoke-test

bin/compile


cat<<EOF >config.json
{
  "suite_name"           : $(echo $file_data | jq .smoke_test.suite_name),
  "api"                  : $(echo $file_data | jq .env.api),
  "apps_domain"          : $(echo $file_data | jq .env.apps_domain),
  "user"                 : $(echo $file_data | jq .env.user),
  "password"             : $(echo $file_data | jq .env.password),
  "org"                  : $(echo $file_data | jq .smoke_test.org),
  "space"                : $(echo $file_data | jq .smoke_test.space),
  "cleanup"              : $(echo $file_data | jq .smoke_test.cleanup),
  "use_existing_org"     : $(echo $file_data | jq .smoke_test.use_existing_org),
  "use_existing_space"   : $(echo $file_data | jq .smoke_test.use_existing_space),
  "logging_app"          : $(echo $file_data | jq .smoke_test.logging_app),
  "runtime_app"          : $(echo $file_data | jq .smoke_test.runtime_app),
  "enable_windows_tests" : $(echo $file_data | jq .smoke_test.enable_windows_tests),
  "backend"              : $(echo $file_data | jq .smoke_test.backend),
  "skip_ssl_validation"  : $(echo $file_data | jq .smoke_test.skip_ssl_validation)
}
EOF

root=$(pwd)
set -x 
CONFIG=$root/config.json bin/test -nodes=2 -v

